services:
  - type: web
    name: sales-overview-api
    env: node
    region: oregon
    plan: free
    repo: https://github.com/chongrayen/Sales-Overview-Website
    branch: main
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: WORKBOOKS_DIR
        value: workbooks
